"""
Itt vannak definiálva azok a változók, amik nem változnak a program futása során,
 továbbá függetlenek más változktól.
"""
HOST_LANE_PATH = '/tmp/'  # Itt kell átírni a képadatbázis helyét
# (ha újra kell tanítani a hálót). pl "/home/gabi/DATA/TRAFFIC/APOLLOSCAPE/"
SSID_USED_BY_DROIDCAM = "VodafoneMobileWiFi-AB7F5E"  # Itt kell átírni a wifi nevét
# (ha ki akarjuk próbálni droidcam kamerával).
IP_USED_BY_DROIDCAM = "192.168.0.139"  # Itt kell megadni azt az ip címet, amit a telefonon futtatott
# droidcam ír ki. Csak akkor változnak a beállítások, ha más telefont használunk, vagy másik wifire csatlakozunk.
ALL = "--all"
ALL_PERMISSION = "777"
AUTO_REMOVE = "--rm"
BASH = "bash"
BLACK = "black"
BUILDERNAME = "-M"
CAMERA_ROWS, CAMERA_COLS = 480, 640
CHMOD = "chmod"
COMMIT = "commit"
CONTAINER = "container"
CONTAINER_NAME = "CUSTOM_CONTAINER_NAME"
CURR_DIR = "."
DROIDCAM = "droidcam-cli"
DEFAULT_DROIDCAM_PORT = "4747"
DOCKER = "sudo docker"
DONT_CAPTURE_OUTPUT = "-s"
DOT = "."
DOUBLE_QUOTE = '"'
ENABLE_DISPLAY_HOST = "xhost +local:"
FORCE = "-f"
GIT = "git"
HTML = "html"
IMAGE = "image"
IMAGES = "images"
INTERACTIVE = "-i"
INTERPRET = "-c"
LANE = "lane"
LATEXPDF = "latexpdf"
LIST = "list"
PRIVATE = "_"
PRUNE = "prune"
PYTEST = "pytest"
PYTHON = "python"
RECURSIVE = "--recursive"
REMOVE = "rm"
RUN = "run"
SHARE_HARDWARE = "--privileged"
SHARE_IPC = "--ipc=host"
SHARE_NET = "--net=host"
SPACE = " "
SPHINX_BUILD = "sphinx-build"
SUDO = "sudo"
SSID_MONOR = "W"
TENSORFLOW_VERSION = "1.12.0"
TTY = "-t"
USE_GPU = "--gpus all"
X11_PATH = "/tmp/.X11-unix"
EMBER = "Ember"
BICIKLI = "Bicikli"
AUTO = "Auto"
MOTOR = "Motor"
BUSZ = "Busz"
VONAT = "Vonat"
KAMION = "Kamion"
JELZOLAMPA = "Jelzolampa"
STOPTABLA = "Stoptabla"
